/*
 * File: jquery.flexisel.js
 * Version: 1.0.2
 * Description: Responsive carousel jQuery plugin
 * Author: 9bit Studios
 * Copyright 2012, 9bit Studios
 * http://www.9bitstudios.com
 * Free to use and abuse under the MIT license.
 * http://www.opensource.org/licenses/mit-license.php
 */
(function($){$.fn.flexisel=function(options){var defaults=$.extend({visibleItems:4,animationSpeed:200,autoPlay:false,autoPlaySpeed:3000,pauseOnHover:true,setMaxWidthAndHeight:false,enableResponsiveBreakpoints:true,clone:false,itemSelector:null,margin:30,moveSlide:2,scroll:'right',vertical:false,responsiveBreakpoints:{portrait:{changePoint:480,visibleItems:1},landscape:{changePoint:640,visibleItems:2},tablet:{changePoint:768,visibleItems:3}}},options);var object=$(this);var objectParent=object.parent();var settings=$.extend(defaults,options);var itemsWidth;var itemsHeight;var canNavigate=true;var canNavigateLeft=true;var firstActive=0;var itemsVisible=settings.visibleItems;var itemsMoveSlide=settings.moveSlide;var totalItems=object.children().length;var responsivePoints=[];var methods={init:function(){return this.each(function(){methods.appendHTML();methods.setEventHandlers();methods.initializeItems();});},initializeItems:function(){var listParent=object.parent();var innerHeight=listParent.height();var childSet=object.children();if(settings.vertical){methods.sortResponsiveObject(settings.responsiveBreakpoints);innerHeight=objectParent.height();itemsHeight=(innerHeight-settings.margin*(settings.visibleItems-1))/ settings.visibleItems;childSet.height(itemsHeight);childSet.css('marginTop',settings.margin);listParent.css('maxHeight',innerHeight);if(settings.clone){childSet.last().insertBefore(childSet.first());childSet.last().insertBefore(childSet.first());object.css({'top':-itemsHeight});}}else{methods.sortResponsiveObject(settings.responsiveBreakpoints);var innerWidth=listParent.width();itemsWidth=(innerWidth-settings.margin*(itemsVisible-1))/ itemsVisible;childSet.width(itemsWidth);childSet.css('marginLeft',settings.margin);if(settings.clone){childSet.last().insertBefore(childSet.first());childSet.last().insertBefore(childSet.first());object.css({'left':-itemsWidth});}}
object.fadeIn();$(window).trigger("resize");},appendHTML:function(){if(settings.vertical){object.addClass("nbs-flexisel-ul vertical");object.wrap("<div class='nbs-flexisel-container'><div class='nbs-flexisel-inner vertical'></div></div>");if(settings.itemSelector){object.find(settings.itemSelector).addClass("nbs-flexisel-item vertical");}else{object.children().addClass("nbs-flexisel-item vertical");}}else{object.addClass("nbs-flexisel-ul");object.wrap("<div class='nbs-flexisel-container'><div class='nbs-flexisel-inner'></div></div>");if(settings.itemSelector){object.find(settings.itemSelector).addClass("nbs-flexisel-item");}else{object.children().addClass("nbs-flexisel-item");}}
if(settings.setMaxWidthAndHeight){var baseWidth=$(".nbs-flexisel-item img").width();var baseHeight=$(".nbs-flexisel-item img").height();$(".nbs-flexisel-item img").css("max-width",baseWidth);$(".nbs-flexisel-item img").css("max-height",baseHeight);}
if(settings.vertical){$("<div class='nbs-flexisel-nav'><div class='nbs-flexisel-nav-top'></div><div class='nbs-flexisel-nav-bottom'></div></div>").insertAfter(object);}else{$("<div class='nbs-flexisel-nav'><div class='nbs-flexisel-nav-left'><span>Prev</span></div><div class='nbs-flexisel-nav-right'><span>Next</span></div></div>").insertAfter(object);}
if(settings.clone){var cloneContent=object.children().clone().addClass('clone');object.append(cloneContent);}},setEventHandlers:function(){var listParent=object.parent();var childSet=object.children();if(settings.vertical){var topArrow=listParent.find($(".nbs-flexisel-nav-top"));var bottomArrow=listParent.find($(".nbs-flexisel-nav-bottom"));}else{var leftArrow=listParent.find($(".nbs-flexisel-nav-left"));var rightArrow=listParent.find($(".nbs-flexisel-nav-right"));}
$(window).on("resize",function(event){var innerWidth=$(listParent).width();var innerHeight=$(listParent).parent().parent().height();if(settings.vertical){itemsHeight=(innerHeight-settings.margin*(settings.visibleItems-1))/ settings.visibleItems;childSet.height(itemsHeight);if(settings.clone){object.css({'top':-itemsHeight-2*settings.margin});}else{object.css({'top':-settings.margin});}}else{methods.setResponsiveEvents();itemsWidth=(innerWidth-settings.margin*(itemsVisible-1))/ itemsVisible;childSet.width(itemsWidth);if(settings.clone){object.css({'left':-itemsWidth-2*settings.margin});}else{object.css({'left':-settings.margin});}}
if(settings.vertical){var halfArrowWidth=(topArrow.width())/ 2;var arrowMargin=(innerWidth / 2)-halfArrowWidth;topArrow.css("left",arrowMargin+"px");bottomArrow.css("left",arrowMargin+"px");}else{var halfArrowHeight=(leftArrow.height())/ 2;var arrowMargin=(innerHeight / 2)-halfArrowHeight;leftArrow.css("top",arrowMargin+"px");rightArrow.css("top",arrowMargin+"px");}});$(leftArrow).on("click",function(event){methods.scrollLeft();});$(rightArrow).on("click",function(event){methods.scrollRight();});$(topArrow).on("click",function(event){methods.scrollTop();});$(bottomArrow).on("click",function(event){methods.scrollBottom();});if(settings.pauseOnHover==true){$(".nbs-flexisel-item").on({mouseenter:function(){canNavigate=false;},mouseleave:function(){canNavigate=true;}});}
if(settings.autoPlay==true){setInterval(function(){if(canNavigate==true){if(settings.vertical){if(settings.scroll=='top')methods.scrollTop();else methods.scrollBottom();}else{if(settings.scroll=='right')methods.scrollRight();else methods.scrollLeft();}}},settings.autoPlaySpeed);}},setResponsiveEvents:function(){var contentWidth=$('html').width();if(settings.enableResponsiveBreakpoints){if(responsivePoints.length)var largestCustom=responsivePoints[responsivePoints.length-1].changePoint;for(var i in responsivePoints){if(contentWidth>=largestCustom){itemsVisible=settings.visibleItems;break;}
else{if(contentWidth<responsivePoints[i].changePoint){itemsVisible=responsivePoints[i].visibleItems;break;}
else
continue;}}}},sortResponsiveObject:function(obj){var responsiveObjects=[];for(var i in obj){responsiveObjects.push(obj[i]);}
responsiveObjects.sort(function(a,b){return a.changePoint-b.changePoint;});responsivePoints=responsiveObjects;},scrollLeft:function(){if(object.position().left<-settings.margin){if(canNavigate==true){canNavigate=false;var listParent=object.parent();var innerWidth=listParent.width();itemsWidth=(innerWidth-settings.margin*(itemsVisible-1))/ itemsVisible+settings.margin;var childSet=object.children();if(!settings.clone){itemsMoveSlide=settings.moveSlide;if(itemsMoveSlide>firstActive)itemsMoveSlide=firstActive;if(itemsMoveSlide>itemsVisible)itemsMoveSlide=itemsVisible;firstActive-=itemsMoveSlide;}
object.animate({'left':"+="+itemsWidth*itemsMoveSlide},{queue:false,duration:settings.animationSpeed,easing:"linear",complete:function(){if(settings.clone){childSet.slice(-itemsMoveSlide).insertBefore(childSet.first());}
methods.adjustScroll();canNavigate=true;canNavigateLeft=true;}});}}else{}},scrollRight:function(){var childSet=object.children();if(!settings.clone){itemsMoveSlide=settings.moveSlide;if(childSet.length<=itemsVisible)return;var elcanNext=childSet.length-firstActive-itemsVisible;if(itemsMoveSlide>elcanNext)itemsMoveSlide=elcanNext;if(itemsMoveSlide>itemsVisible)itemsMoveSlide=itemsVisible;firstActive+=itemsMoveSlide;}
var listParent=object.parent();var innerWidth=listParent.width();itemsWidth=(innerWidth-settings.margin*(itemsVisible-1))/ itemsVisible+settings.margin;var difObject=(itemsWidth-innerWidth);var objPosition=(object.position().left+((totalItems-itemsVisible)*itemsWidth)-innerWidth);if((difObject<=Math.ceil(objPosition))&&(!settings.clone)){if(canNavigate==true){canNavigate=false;object.animate({'left':"-="+itemsWidth*itemsMoveSlide},{queue:false,duration:settings.animationSpeed,easing:"linear",complete:function(){methods.adjustScroll();canNavigate=true;}});}}else if(settings.clone){if(canNavigate==true){canNavigate=false;object.animate({'left':"-="+itemsWidth*itemsMoveSlide},{queue:false,duration:settings.animationSpeed,easing:"linear",complete:function(){childSet.slice(0,itemsMoveSlide).insertAfter(childSet.last());methods.adjustScroll();canNavigate=true;}});}}else{if(canNavigateLeft==true){canNavigateLeft=false;object.animate({'left':"-="+itemsWidth*itemsMoveSlide},{queue:false,duration:settings.animationSpeed,easing:"linear",complete:function(){methods.adjustScroll();canNavigateLeft=false;}});}};},adjustScroll:function(){var listParent=object.parent();var childSet=object.children();if(settings.vertical){var innerHeight=$(listParent).parent().parent().height();itemsHeight=(innerHeight-settings.margin*(settings.visibleItems-1))/ settings.visibleItems;childSet.height(itemsHeight);if(settings.clone){object.css({'top':-(itemsHeight+settings.margin)*itemsMoveSlide-settings.margin});}}else{var innerWidth=listParent.width();itemsWidth=(innerWidth-settings.margin*(itemsVisible-1))/ itemsVisible;childSet.width(itemsWidth);if(settings.clone){object.css({'left':-(itemsWidth+settings.margin)*itemsMoveSlide-settings.margin});}}},scrollTop:function(){if(object.position().top<-settings.margin){if(canNavigate==true){canNavigate=false;var listParent=object.parent();var innerHeight=$(listParent).parent().parent().height();itemsHeight=(innerHeight-settings.margin*(settings.visibleItems-1))/ settings.visibleItems+settings.margin;var childSet=object.children();object.animate({'top':"+="+(itemsHeight)*itemsMoveSlide},{queue:false,duration:settings.animationSpeed,easing:"linear",complete:function(){if(settings.clone){childSet.slice(-itemsMoveSlide).insertBefore(childSet.first());}
methods.adjustScroll();canNavigate=true;}});}}},scrollBottom:function(){var listParent=object.parent();var innerHeight=$(listParent).parent().parent().height();itemsHeight=(innerHeight-settings.margin*(settings.visibleItems-1))/ settings.visibleItems+settings.margin;var difObject=(itemsHeight-innerHeight);var objPosition=(object.position().top+((totalItems-settings.visibleItems)*itemsHeight)-innerHeight);if((difObject<=Math.ceil(objPosition))&&(!settings.clone)){if(canNavigate==true){canNavigate=false;object.animate({'top':"-="+(itemsHeight)*itemsMoveSlide},{queue:false,duration:settings.animationSpeed,easing:"linear",complete:function(){methods.adjustScroll();canNavigate=true;}});}}else if(settings.clone){if(canNavigate==true){canNavigate=false;var childSet=object.children();object.animate({'top':"-="+itemsHeight},{queue:false,duration:settings.animationSpeed,easing:"linear",complete:function(){childSet.slice(0,itemsMoveSlide).insertAfter(childSet.last());methods.adjustScroll();canNavigate=true;}});}};}};if(methods[options]){return methods[options].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof options==='object'||!options){return methods.init.apply(this);}else{$.error('Method "'+method+'" does not exist in flexisel plugin!');}};})(jQuery);